// SPDX-License-Identifier: GPL-2.0-only
//
//! Wire-level constants for init's master service surface and per-client
//! request MPs. Mirrors the labels POSIX wrappers send plus the few
//! admin labels mmsrv uses to forward faults.

use trona_protocol::posix::{
    INIT_CRED, INIT_CRED_SUB_GETEGID, INIT_CRED_SUB_GETEUID, INIT_CRED_SUB_GETGID,
    INIT_CRED_SUB_GETGROUPS, INIT_CRED_SUB_GETRESGID, INIT_CRED_SUB_GETRESUID,
    INIT_CRED_SUB_GETUID, INIT_CRED_SUB_SETEGID, INIT_CRED_SUB_SETEUID, INIT_CRED_SUB_SETGID,
    INIT_CRED_SUB_SETGROUPS, INIT_CRED_SUB_SETREGID, INIT_CRED_SUB_SETRESGID,
    INIT_CRED_SUB_SETRESUID, INIT_CRED_SUB_SETREUID, INIT_CRED_SUB_SETUID, INIT_CRED_SUB_UMASK,
    INIT_DEBUG_DUMP_TABLE, INIT_EXEC, INIT_EXIT, INIT_FORK, INIT_GET_ABI_VERSION,
    INIT_GET_BOOTINFO_FRAME, INIT_GET_PID, INIT_GET_PPID, INIT_GET_PROC_INFO,
    INIT_GET_PROC_INFO_SUB_GET_PROC_INFO, INIT_GET_PROC_INFO_SUB_LIST_PIDS, INIT_ITIMER,
    INIT_ITIMER_SUB_GET, INIT_ITIMER_SUB_SET, INIT_KILL, INIT_KILL_PGID, INIT_LIFECYCLE_SUBSCRIBE,
    INIT_LIFECYCLE_UNSUBSCRIBE, INIT_NOTIFY_READY, INIT_PGRP_SESSION,
    INIT_PGRP_SUB_GET_SID_PGID_BY_BADGE, INIT_PGRP_SUB_GETPGID, INIT_PGRP_SUB_GETPGID_BY_BADGE,
    INIT_PGRP_SUB_GETPGRP, INIT_PGRP_SUB_GETSID, INIT_PGRP_SUB_GETSID_BY_BADGE,
    INIT_PGRP_SUB_SETPGID, INIT_PGRP_SUB_SETSID, INIT_REAP_BADGE, INIT_REGISTER_FAULT_OBSERVER,
    INIT_REGISTER_INTERFACE, INIT_REPORT_FAULT, INIT_RESOLVE_INTERFACE, INIT_RLIMIT,
    INIT_RLIMIT_SUB_GET, INIT_RLIMIT_SUB_SET, INIT_SERVICE_QUERY, INIT_SIGACTION,
    INIT_SIGPENDING_DUMP, INIT_SPAWN, INIT_THREAD, INIT_THREAD_SUB_CREATE, INIT_THREAD_SUB_DETACH,
    INIT_THREAD_SUB_EXIT, INIT_THREAD_SUB_GET_THREAD_CAPS, INIT_THREAD_SUB_JOIN,
    INIT_THREAD_SUB_REAP, INIT_UNREGISTER_FAULT_OBSERVER, INIT_WAIT,
};

// The `GET_PROC_INFO` sub-op family is canonically defined in
// `trona_protocol::init` — its doc comments specify the exact reply
// layouts VFS decodes (PROC_INFO_FULL regs[1..11], EXE_PATH=0x0A, the
// extended CPU_INFO / CLIENT_VM_STATS / PROC_INFO_FULL ops).
// `posix.rs` carries a stale lower-numbered copy (EXE_PATH=0x07,
// DUMP_PENDING=0x08); the init server must use the `init.rs` values so
// VFS↔init sub-op numbers match. Only `GET_PROC_INFO` (0x00) and
// `LIST_PIDS` (0x01) are posix-only and stay imported above.
use trona_protocol::init::{
    INIT_GET_PROC_INFO_SUB_GET_ARGV, INIT_GET_PROC_INFO_SUB_GET_EXE_PATH,
    INIT_GET_PROC_INFO_SUB_GET_KINFO_PROC, INIT_GET_PROC_INFO_SUB_GET_KINFO_PROC_PAGE,
    INIT_GET_PROC_INFO_SUB_GET_PROC_INFO_FULL, INIT_GET_PROC_INFO_SUB_GET_PROC_TIMES,
    INIT_GET_PROC_INFO_SUB_GET_SYSTEM_STATS, INIT_GET_PROC_INFO_SUB_LIST_PIDS_BUF,
};

// Re-export for compactness inside the supervisor.
pub const LABEL_GET_ABI_VERSION: u64 = INIT_GET_ABI_VERSION;
pub const LABEL_GET_BOOTINFO_FRAME: u64 = INIT_GET_BOOTINFO_FRAME;
pub const LABEL_SPAWN: u64 = INIT_SPAWN;
pub const LABEL_FORK: u64 = INIT_FORK;
pub const LABEL_EXEC: u64 = INIT_EXEC;
pub const LABEL_EXIT: u64 = INIT_EXIT;
pub const LABEL_GET_PID: u64 = INIT_GET_PID;
pub const LABEL_GET_PPID: u64 = INIT_GET_PPID;
pub const LABEL_REGISTER_INTERFACE: u64 = INIT_REGISTER_INTERFACE;
pub const LABEL_RESOLVE_INTERFACE: u64 = INIT_RESOLVE_INTERFACE;
pub const LABEL_REAP_BADGE: u64 = INIT_REAP_BADGE;

pub const LABEL_WAIT: u64 = INIT_WAIT;
pub const LABEL_KILL: u64 = INIT_KILL;
pub const LABEL_KILL_PGID: u64 = INIT_KILL_PGID;
pub const LABEL_SIGACTION: u64 = INIT_SIGACTION;
pub const LABEL_SIGPENDING_DUMP: u64 = INIT_SIGPENDING_DUMP;

pub const LABEL_CRED: u64 = INIT_CRED;
pub const LABEL_PGRP_SESSION: u64 = INIT_PGRP_SESSION;
pub const LABEL_RLIMIT: u64 = INIT_RLIMIT;
pub const LABEL_ITIMER: u64 = INIT_ITIMER;
pub const LABEL_THREAD: u64 = INIT_THREAD;
pub const LABEL_GET_PROC_INFO: u64 = INIT_GET_PROC_INFO;
pub const LABEL_SERVICE_QUERY: u64 = INIT_SERVICE_QUERY;

pub const LABEL_LIFECYCLE_SUBSCRIBE: u64 = INIT_LIFECYCLE_SUBSCRIBE;
pub const LABEL_LIFECYCLE_UNSUBSCRIBE: u64 = INIT_LIFECYCLE_UNSUBSCRIBE;
pub const LABEL_REPORT_FAULT: u64 = INIT_REPORT_FAULT;
pub const LABEL_REGISTER_FAULT_OBSERVER: u64 = INIT_REGISTER_FAULT_OBSERVER;
pub const LABEL_UNREGISTER_FAULT_OBSERVER: u64 = INIT_UNREGISTER_FAULT_OBSERVER;
pub const LABEL_CORE_READY: u64 = trona_protocol::init::INIT_CORE_READY;
pub const LABEL_NOTIFY_READY: u64 = INIT_NOTIFY_READY;
pub const LABEL_DEBUG_DUMP_TABLE: u64 = INIT_DEBUG_DUMP_TABLE;

// CRED sub-ops (regs[0]).
pub const CRED_SUB_GETUID: u64 = INIT_CRED_SUB_GETUID;
pub const CRED_SUB_GETGID: u64 = INIT_CRED_SUB_GETGID;
pub const CRED_SUB_GETEUID: u64 = INIT_CRED_SUB_GETEUID;
pub const CRED_SUB_GETEGID: u64 = INIT_CRED_SUB_GETEGID;
pub const CRED_SUB_GETGROUPS: u64 = INIT_CRED_SUB_GETGROUPS;
pub const CRED_SUB_SETUID: u64 = INIT_CRED_SUB_SETUID;
pub const CRED_SUB_SETGID: u64 = INIT_CRED_SUB_SETGID;
pub const CRED_SUB_SETEUID: u64 = INIT_CRED_SUB_SETEUID;
pub const CRED_SUB_SETEGID: u64 = INIT_CRED_SUB_SETEGID;
pub const CRED_SUB_SETREUID: u64 = INIT_CRED_SUB_SETREUID;
pub const CRED_SUB_SETREGID: u64 = INIT_CRED_SUB_SETREGID;
pub const CRED_SUB_SETGROUPS: u64 = INIT_CRED_SUB_SETGROUPS;
pub const CRED_SUB_GETRESUID: u64 = INIT_CRED_SUB_GETRESUID;
pub const CRED_SUB_GETRESGID: u64 = INIT_CRED_SUB_GETRESGID;
pub const CRED_SUB_SETRESUID: u64 = INIT_CRED_SUB_SETRESUID;
pub const CRED_SUB_SETRESGID: u64 = INIT_CRED_SUB_SETRESGID;
pub const CRED_SUB_UMASK: u64 = INIT_CRED_SUB_UMASK;

// PGRP_SESSION sub-ops (regs[0]).
pub const PGRP_SUB_SETPGID: u64 = INIT_PGRP_SUB_SETPGID;
pub const PGRP_SUB_GETPGID: u64 = INIT_PGRP_SUB_GETPGID;
pub const PGRP_SUB_GETPGRP: u64 = INIT_PGRP_SUB_GETPGRP;
pub const PGRP_SUB_SETSID: u64 = INIT_PGRP_SUB_SETSID;
pub const PGRP_SUB_GETSID: u64 = INIT_PGRP_SUB_GETSID;
pub const PGRP_SUB_GETPGID_BY_BADGE: u64 = INIT_PGRP_SUB_GETPGID_BY_BADGE;
pub const PGRP_SUB_GETSID_BY_BADGE: u64 = INIT_PGRP_SUB_GETSID_BY_BADGE;
pub const PGRP_SUB_GET_SID_PGID_BY_BADGE: u64 = INIT_PGRP_SUB_GET_SID_PGID_BY_BADGE;

// RLIMIT sub-ops (regs[0]).
pub const RLIMIT_SUB_GET: u64 = INIT_RLIMIT_SUB_GET;
pub const RLIMIT_SUB_SET: u64 = INIT_RLIMIT_SUB_SET;

// ITIMER sub-ops (regs[0]).
pub const ITIMER_SUB_GET: u64 = INIT_ITIMER_SUB_GET;
pub const ITIMER_SUB_SET: u64 = INIT_ITIMER_SUB_SET;

// THREAD sub-ops (regs[0]).
pub const THREAD_SUB_CREATE: u64 = INIT_THREAD_SUB_CREATE;
pub const THREAD_SUB_EXIT: u64 = INIT_THREAD_SUB_EXIT;
pub const THREAD_SUB_JOIN: u64 = INIT_THREAD_SUB_JOIN;
pub const THREAD_SUB_DETACH: u64 = INIT_THREAD_SUB_DETACH;
pub const THREAD_SUB_REAP: u64 = INIT_THREAD_SUB_REAP;
pub const THREAD_SUB_GET_THREAD_CAPS: u64 = INIT_THREAD_SUB_GET_THREAD_CAPS;

// GET_PROC_INFO sub-ops (regs[0]).
pub const GPI_SUB_GET_PROC_INFO: u64 = INIT_GET_PROC_INFO_SUB_GET_PROC_INFO;
pub const GPI_SUB_LIST_PIDS: u64 = INIT_GET_PROC_INFO_SUB_LIST_PIDS;
pub const GPI_SUB_GET_PROC_TIMES: u64 = INIT_GET_PROC_INFO_SUB_GET_PROC_TIMES;
pub const GPI_SUB_GET_SYSTEM_STATS: u64 = INIT_GET_PROC_INFO_SUB_GET_SYSTEM_STATS;
pub const GPI_SUB_GET_KINFO_PROC: u64 = INIT_GET_PROC_INFO_SUB_GET_KINFO_PROC;
pub const GPI_SUB_LIST_PIDS_BUF: u64 = INIT_GET_PROC_INFO_SUB_LIST_PIDS_BUF;
pub const GPI_SUB_GET_ARGV: u64 = INIT_GET_PROC_INFO_SUB_GET_ARGV;
pub const GPI_SUB_GET_EXE_PATH: u64 = INIT_GET_PROC_INFO_SUB_GET_EXE_PATH;
pub const GPI_SUB_GET_PROC_INFO_FULL: u64 = INIT_GET_PROC_INFO_SUB_GET_PROC_INFO_FULL;
pub const GPI_SUB_GET_KINFO_PROC_PAGE: u64 = INIT_GET_PROC_INFO_SUB_GET_KINFO_PROC_PAGE;

// Cookie kinds for init's `EventLoop`. Encoded into the
// upper byte of the kernel cookie via
// [`trona_server::event_loop::encode_cookie`]; `live_gen` is
// supplied by `state.cookie_table.arm` so stale fires after teardown
// drop on dispatch.
//
// `INIT_COOKIE_KIND_REQUEST_MP` carries the per-client request MP
// recv side. The target keeps its semantic payload (`client_id`)
// inside the dispatcher's `CookieTable<InitTarget>` entry, not in
// the cookie itself — the cookie's `slot` field is opaque to callers.

pub const INIT_COOKIE_KIND_REQUEST_MP: u8 = 0x01;
pub const INIT_COOKIE_KIND_MASTER_MP: u8 = 0x02;
pub const INIT_COOKIE_KIND_WORKER_COMPLETION: u8 = 0x03;
pub const INIT_COOKIE_KIND_CONTROL_TIMER: u8 = 0x05;
pub const INIT_COOKIE_KIND_NAMESRV_REGISTER_EVENT: u8 = 0x06;

/// Discriminator for `INIT_REPORT_FAULT.regs[2]` — kind of fault mmsrv
/// is forwarding. Mirrors `KERNITE_FAULT_*` codes the kernel uses on the
/// fault MP itself.
pub const FAULT_KIND_PAGE_FAULT: u64 = uapi::KERNITE_FAULT_PAGE_FAULT;
pub const FAULT_KIND_ILLEGAL_INSTRUCTION: u64 = uapi::KERNITE_FAULT_ILLEGAL_INSTRUCTION;
pub const FAULT_KIND_BREAKPOINT: u64 = uapi::KERNITE_FAULT_BREAKPOINT;
pub const FAULT_KIND_USER_EXCEPTION: u64 = uapi::KERNITE_FAULT_USER_EXCEPTION;
pub const FAULT_KIND_OOM: u64 = uapi::KERNITE_FAULT_OOM;
pub const FAULT_KIND_CAPABILITY: u64 = uapi::KERNITE_FAULT_CAP;

/// Action codes init returns to mmsrv in `INIT_REPORT_FAULT.reply.regs[0]`.
pub const FAULT_ACTION_RESUME: u64 = 0;
pub const FAULT_ACTION_KILL: u64 = 1;
pub const FAULT_ACTION_KILL_GROUP: u64 = 2;

/// Per-core-service identification badges init stamps on the
/// `ROLE_INIT_CONTROL` send cap it delivers to each core service. Those
/// servers send *to* init through that cap; init's reactor and fault
/// dispatcher authenticate inbound messages by the badge so each sender is
/// uniquely identified — only mmsrv may issue `INIT_REPORT_FAULT`, and each
/// `INIT_CORE_READY` is matched to the exact server init just spawned. This is
/// the server→init direction, unrelated to the per-client control caps that
/// authorize the init→server admin surface.
pub const INIT_BADGE_FROM_MMSRV: u64 = 0xF000_0000_0000_0002;
pub const INIT_BADGE_FROM_NAMESRV: u64 = 0xF000_0000_0000_0004;
pub const INIT_BADGE_FROM_RSRCSRV: u64 = 0xF000_0000_0000_0005;
