# SaltyOS login configuration
# Used by login(1) and su(1)

default:\
	:path=/usr/bin /bin /usr/sbin /sbin:\
	:umask=022:\
	:welcome=/etc/motd:\
	:passwd_format=sha512:

root:\
	:path=/usr/bin /bin /usr/sbin /sbin:\
	:umask=022:\
	:welcome=/etc/motd:\
	:passwd_format=sha512:
