pub const KERNITE_ABI_VERSION: u64 = kernite_bindgen_u64_KERNITE_ABI_VERSION;
pub const KERNITE_SYS_INVOKE: u64 = kernite_bindgen_u64_KERNITE_SYS_INVOKE;
pub const KERNITE_OK: u64 = kernite_bindgen_u64_KERNITE_OK;
pub const KERNITE_ERR_INVALID_CAPABILITY: u64 = kernite_bindgen_u64_KERNITE_ERR_INVALID_CAPABILITY;
pub const KERNITE_ERR_INVALID_OPERATION: u64 = kernite_bindgen_u64_KERNITE_ERR_INVALID_OPERATION;
pub const KERNITE_ERR_INSUFFICIENT_RIGHTS: u64 =
    kernite_bindgen_u64_KERNITE_ERR_INSUFFICIENT_RIGHTS;
pub const KERNITE_ERR_INVALID_ARGUMENT: u64 = kernite_bindgen_u64_KERNITE_ERR_INVALID_ARGUMENT;
pub const KERNITE_ERR_OUT_OF_MEMORY: u64 = kernite_bindgen_u64_KERNITE_ERR_OUT_OF_MEMORY;
pub const KERNITE_ERR_NOT_FOUND: u64 = kernite_bindgen_u64_KERNITE_ERR_NOT_FOUND;
pub const KERNITE_ERR_BUSY: u64 = kernite_bindgen_u64_KERNITE_ERR_BUSY;
pub const KERNITE_ERR_ALREADY_EXISTS: u64 = kernite_bindgen_u64_KERNITE_ERR_ALREADY_EXISTS;
pub const KERNITE_ERR_WOULD_BLOCK: u64 = kernite_bindgen_u64_KERNITE_ERR_WOULD_BLOCK;
pub const KERNITE_ERR_BAD_ADDRESS: u64 = kernite_bindgen_u64_KERNITE_ERR_BAD_ADDRESS;
pub const KERNITE_ERR_OUT_OF_RANGE: u64 = kernite_bindgen_u64_KERNITE_ERR_OUT_OF_RANGE;
pub const KERNITE_ERR_CANCELLED: u64 = kernite_bindgen_u64_KERNITE_ERR_CANCELLED;
pub const KERNITE_ERR_RESTART: u64 = kernite_bindgen_u64_KERNITE_ERR_RESTART;
pub const KERNITE_ERR_DEADLOCK: u64 = kernite_bindgen_u64_KERNITE_ERR_DEADLOCK;
pub const KERNITE_ERR_INTERRUPTED: u64 = kernite_bindgen_u64_KERNITE_ERR_INTERRUPTED;
pub const KERNITE_ERR_TOO_LARGE: u64 = kernite_bindgen_u64_KERNITE_ERR_TOO_LARGE;
pub const KERNITE_ERR_NOT_SUPPORTED: u64 = kernite_bindgen_u64_KERNITE_ERR_NOT_SUPPORTED;
pub const KERNITE_ERR_READONLY: u64 = kernite_bindgen_u64_KERNITE_ERR_READONLY;
pub const KERNITE_ERR_SLOT_OCCUPIED: u64 = kernite_bindgen_u64_KERNITE_ERR_SLOT_OCCUPIED;
pub const KERNITE_ERR_ALREADY_MAPPED: u64 = kernite_bindgen_u64_KERNITE_ERR_ALREADY_MAPPED;
pub const KERNITE_ERR_PEER_CLOSED: u64 = kernite_bindgen_u64_KERNITE_ERR_PEER_CLOSED;
pub const KERNITE_ERR_QUEUE_OVERFLOW: u64 = kernite_bindgen_u64_KERNITE_ERR_QUEUE_OVERFLOW;
pub const KERNITE_ERR_WATCH_CANCELLED: u64 = kernite_bindgen_u64_KERNITE_ERR_WATCH_CANCELLED;
pub const KERNITE_ERR_ABI_MISMATCH: u64 = kernite_bindgen_u64_KERNITE_ERR_ABI_MISMATCH;
pub const KERNITE_ERR_IO_ERROR: u64 = kernite_bindgen_u64_KERNITE_ERR_IO_ERROR;
pub const KERNITE_ERR_TIMED_OUT: u64 = kernite_bindgen_u64_KERNITE_ERR_TIMED_OUT;
pub const KERNITE_ERR_PENDING: u64 = kernite_bindgen_u64_KERNITE_ERR_PENDING;
pub const KERNITE_ERR_INSUFFICIENT_RESOURCES: u64 =
    kernite_bindgen_u64_KERNITE_ERR_INSUFFICIENT_RESOURCES;
pub const KERNITE_OBJ_NULL: u64 = kernite_bindgen_u64_KERNITE_OBJ_NULL;
pub const KERNITE_OBJ_UNTYPED: u64 = kernite_bindgen_u64_KERNITE_OBJ_UNTYPED;
pub const KERNITE_OBJ_TCB: u64 = kernite_bindgen_u64_KERNITE_OBJ_TCB;
pub const KERNITE_OBJ_CNODE: u64 = kernite_bindgen_u64_KERNITE_OBJ_CNODE;
pub const KERNITE_OBJ_VSPACE: u64 = kernite_bindgen_u64_KERNITE_OBJ_VSPACE;
pub const KERNITE_OBJ_FRAME: u64 = kernite_bindgen_u64_KERNITE_OBJ_FRAME;
pub const KERNITE_OBJ_IRQ_HANDLER: u64 = kernite_bindgen_u64_KERNITE_OBJ_IRQ_HANDLER;
pub const KERNITE_OBJ_IO_PORT: u64 = kernite_bindgen_u64_KERNITE_OBJ_IO_PORT;
pub const KERNITE_OBJ_SCHED_CONTEXT: u64 = kernite_bindgen_u64_KERNITE_OBJ_SCHED_CONTEXT;
pub const KERNITE_OBJ_MEMORY_OBJECT: u64 = kernite_bindgen_u64_KERNITE_OBJ_MEMORY_OBJECT;
pub const KERNITE_OBJ_EVENT_QUEUE: u64 = kernite_bindgen_u64_KERNITE_OBJ_EVENT_QUEUE;
pub const KERNITE_OBJ_WATCH: u64 = kernite_bindgen_u64_KERNITE_OBJ_WATCH;
pub const KERNITE_OBJ_MESSAGE_PIPE: u64 = kernite_bindgen_u64_KERNITE_OBJ_MESSAGE_PIPE;
pub const KERNITE_OBJ_DATA_PIPE: u64 = kernite_bindgen_u64_KERNITE_OBJ_DATA_PIPE;
pub const KERNITE_OBJ_TIMER: u64 = kernite_bindgen_u64_KERNITE_OBJ_TIMER;
pub const KERNITE_OBJ_KERNEL_RNG: u64 = kernite_bindgen_u64_KERNITE_OBJ_KERNEL_RNG;
pub const KERNITE_OBJ_SYSTEM_CONTROL: u64 = kernite_bindgen_u64_KERNITE_OBJ_SYSTEM_CONTROL;
pub const KERNITE_OBJ_CLOCK: u64 = kernite_bindgen_u64_KERNITE_OBJ_CLOCK;
pub const KERNITE_OBJ_SYSTEM_INFO: u64 = kernite_bindgen_u64_KERNITE_OBJ_SYSTEM_INFO;
pub const KERNITE_OBJ_KERNEL_DEBUG: u64 = kernite_bindgen_u64_KERNITE_OBJ_KERNEL_DEBUG;
pub const KERNITE_OBJ_MESSAGE_PIPE_CORE: u64 = kernite_bindgen_u64_KERNITE_OBJ_MESSAGE_PIPE_CORE;
pub const KERNITE_OBJ_DATA_PIPE_CORE: u64 = kernite_bindgen_u64_KERNITE_OBJ_DATA_PIPE_CORE;
pub const KERNITE_OBJ_PAGER: u64 = kernite_bindgen_u64_KERNITE_OBJ_PAGER;
pub const KERNITE_OBJ_DEVICE_CONTROL: u64 = kernite_bindgen_u64_KERNITE_OBJ_DEVICE_CONTROL;
pub const KERNITE_OBJ_VM_HIERARCHY_STATE: u64 = kernite_bindgen_u64_KERNITE_OBJ_VM_HIERARCHY_STATE;
pub const KERNITE_OBJ_EXEC_AUTHORITY: u64 = kernite_bindgen_u64_KERNITE_OBJ_EXEC_AUTHORITY;
pub const KERNITE_OBJ_PAGE_TABLE: u64 = kernite_bindgen_u64_KERNITE_OBJ_PAGE_TABLE;
pub const KERNITE_PAGE_BYTES: u64 = kernite_bindgen_u64_KERNITE_PAGE_BYTES;
pub const KERNITE_PAGE_TABLE_BYTES: u64 = kernite_bindgen_u64_KERNITE_PAGE_TABLE_BYTES;
pub const KERNITE_CNODE_DEFAULT_SIZE_BITS: u64 =
    kernite_bindgen_u64_KERNITE_CNODE_DEFAULT_SIZE_BITS;
pub const KERNITE_CNODE_MIN_SIZE_BITS: u64 = kernite_bindgen_u64_KERNITE_CNODE_MIN_SIZE_BITS;
pub const KERNITE_CNODE_MAX_SIZE_BITS: u64 = kernite_bindgen_u64_KERNITE_CNODE_MAX_SIZE_BITS;
pub const KERNITE_CNODE_HEADER_BYTES: u64 = kernite_bindgen_u64_KERNITE_CNODE_HEADER_BYTES;
pub const KERNITE_CNODE_SLOT_BYTES: u64 = kernite_bindgen_u64_KERNITE_CNODE_SLOT_BYTES;
pub const KERNITE_VSPACE_TRACKING_BYTES: u64 = kernite_bindgen_u64_KERNITE_VSPACE_TRACKING_BYTES;
pub const KERNITE_VSPACE_BYTES: u64 = kernite_bindgen_u64_KERNITE_VSPACE_BYTES;
pub const KERNITE_MO_HEADER_BYTES: u64 = kernite_bindgen_u64_KERNITE_MO_HEADER_BYTES;
pub const KERNITE_TCB_BYTES: u64 = kernite_bindgen_u64_KERNITE_TCB_BYTES;
pub const KERNITE_SCHED_CONTEXT_BYTES: u64 = kernite_bindgen_u64_KERNITE_SCHED_CONTEXT_BYTES;
pub const KERNITE_IRQ_HANDLER_BYTES: u64 = kernite_bindgen_u64_KERNITE_IRQ_HANDLER_BYTES;
pub const KERNITE_IO_PORT_BYTES: u64 = kernite_bindgen_u64_KERNITE_IO_PORT_BYTES;
pub const KERNITE_EVENT_QUEUE_BYTES: u64 = kernite_bindgen_u64_KERNITE_EVENT_QUEUE_BYTES;
pub const KERNITE_WATCH_BYTES: u64 = kernite_bindgen_u64_KERNITE_WATCH_BYTES;
pub const KERNITE_MESSAGE_PIPE_BYTES: u64 = kernite_bindgen_u64_KERNITE_MESSAGE_PIPE_BYTES;
pub const KERNITE_MESSAGE_PIPE_CORE_BYTES: u64 =
    kernite_bindgen_u64_KERNITE_MESSAGE_PIPE_CORE_BYTES;
pub const KERNITE_DATA_PIPE_BYTES: u64 = kernite_bindgen_u64_KERNITE_DATA_PIPE_BYTES;
pub const KERNITE_DATA_PIPE_CORE_BYTES: u64 = kernite_bindgen_u64_KERNITE_DATA_PIPE_CORE_BYTES;
pub const KERNITE_TIMER_BYTES: u64 = kernite_bindgen_u64_KERNITE_TIMER_BYTES;
pub const KERNITE_KERNEL_RNG_BYTES: u64 = kernite_bindgen_u64_KERNITE_KERNEL_RNG_BYTES;
pub const KERNITE_SYSTEM_CONTROL_BYTES: u64 = kernite_bindgen_u64_KERNITE_SYSTEM_CONTROL_BYTES;
pub const KERNITE_CLOCK_BYTES: u64 = kernite_bindgen_u64_KERNITE_CLOCK_BYTES;
pub const KERNITE_SYSTEM_INFO_BYTES: u64 = kernite_bindgen_u64_KERNITE_SYSTEM_INFO_BYTES;
pub const KERNITE_KERNEL_DEBUG_BYTES: u64 = kernite_bindgen_u64_KERNITE_KERNEL_DEBUG_BYTES;
pub const KERNITE_PAGER_BYTES: u64 = kernite_bindgen_u64_KERNITE_PAGER_BYTES;
pub const KERNITE_DEVICE_CONTROL_BYTES: u64 = kernite_bindgen_u64_KERNITE_DEVICE_CONTROL_BYTES;
pub const KERNITE_VM_HIERARCHY_STATE_BYTES: u64 =
    kernite_bindgen_u64_KERNITE_VM_HIERARCHY_STATE_BYTES;
pub const KERNITE_EXEC_AUTHORITY_BYTES: u64 = kernite_bindgen_u64_KERNITE_EXEC_AUTHORITY_BYTES;
pub const KERNITE_CAP_SELF_TCB: u64 = kernite_bindgen_u64_KERNITE_CAP_SELF_TCB;
pub const KERNITE_CAP_SELF_VSPACE: u64 = kernite_bindgen_u64_KERNITE_CAP_SELF_VSPACE;
pub const KERNITE_CAP_SELF_CSPACE: u64 = kernite_bindgen_u64_KERNITE_CAP_SELF_CSPACE;
pub const KERNITE_INV_CNODE_COPY: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_COPY;
pub const KERNITE_INV_CNODE_MINT: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_MINT;
pub const KERNITE_INV_CNODE_MOVE: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_MOVE;
pub const KERNITE_INV_CNODE_MUTATE: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_MUTATE;
pub const KERNITE_INV_CNODE_DELETE: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_DELETE;
pub const KERNITE_INV_CNODE_REVOKE: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_REVOKE;
pub const KERNITE_INV_CNODE_SET_GUARD: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_SET_GUARD;
pub const KERNITE_INV_CNODE_GET_INFO: u64 = kernite_bindgen_u64_KERNITE_INV_CNODE_GET_INFO;
pub const KERNITE_INV_UNTYPED_RETYPE: u64 = kernite_bindgen_u64_KERNITE_INV_UNTYPED_RETYPE;
pub const KERNITE_INV_UNTYPED_RESET: u64 = kernite_bindgen_u64_KERNITE_INV_UNTYPED_RESET;
pub const KERNITE_INV_UNTYPED_GET_STATS: u64 = kernite_bindgen_u64_KERNITE_INV_UNTYPED_GET_STATS;
pub const KERNITE_INV_TCB_CONFIGURE: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_CONFIGURE;
pub const KERNITE_INV_TCB_START: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_START;
pub const KERNITE_INV_TCB_STOP: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_STOP;
pub const KERNITE_INV_TCB_KILL: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_KILL;
pub const KERNITE_INV_TCB_YIELD: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_YIELD;
pub const KERNITE_INV_TCB_GET_STATE: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_GET_STATE;
pub const KERNITE_INV_TCB_GET_ABI_VERSION: u64 =
    kernite_bindgen_u64_KERNITE_INV_TCB_GET_ABI_VERSION;
pub const KERNITE_INV_TCB_SET_INVOKE_DEPTHS: u64 =
    kernite_bindgen_u64_KERNITE_INV_TCB_SET_INVOKE_DEPTHS;
pub const KERNITE_INV_TCB_SET_SPACE: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_SPACE;
pub const KERNITE_INV_TCB_SET_AFFINITY: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_AFFINITY;
pub const KERNITE_INV_TCB_READ_REGISTERS: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_READ_REGISTERS;
pub const KERNITE_INV_TCB_WRITE_REGISTERS: u64 =
    kernite_bindgen_u64_KERNITE_INV_TCB_WRITE_REGISTERS;
pub const KERNITE_INV_TCB_SET_PRIORITY: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_PRIORITY;
pub const KERNITE_INV_TCB_SET_IPC_BUFFER: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_IPC_BUFFER;
pub const KERNITE_INV_TCB_SET_FAULT_PIPE: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_FAULT_PIPE;
pub const KERNITE_INV_TCB_COPY_FPU: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_COPY_FPU;
pub const KERNITE_INV_TCB_SET_TLS_BASE: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_TLS_BASE;
pub const KERNITE_INV_TCB_SET_STACK_BOUNDS: u64 =
    kernite_bindgen_u64_KERNITE_INV_TCB_SET_STACK_BOUNDS;
pub const KERNITE_INV_TCB_SET_SCHED_CLASS: u64 =
    kernite_bindgen_u64_KERNITE_INV_TCB_SET_SCHED_CLASS;
pub const KERNITE_INV_TCB_GET_SPACE_INFO: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_GET_SPACE_INFO;
pub const KERNITE_INV_TCB_GET_CPU_TIMES: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_GET_CPU_TIMES;
pub const KERNITE_INV_TCB_GET_TRACE_ID: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_GET_TRACE_ID;
pub const KERNITE_INV_TCB_SET_ABI_TP: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_SET_ABI_TP;
pub const KERNITE_INV_TCB_EXIT_SELF: u64 = kernite_bindgen_u64_KERNITE_INV_TCB_EXIT_SELF;
pub const KERNITE_INV_VSPACE_MAP: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP;
pub const KERNITE_INV_VSPACE_UNMAP: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_UNMAP;
pub const KERNITE_INV_VSPACE_MAP_PT: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_PT;
pub const KERNITE_INV_VSPACE_WALK: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_WALK;
pub const KERNITE_INV_VSPACE_COPY_PAGE: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_COPY_PAGE;
pub const KERNITE_INV_VSPACE_MAP_DEVICE: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_DEVICE;
pub const KERNITE_INV_VSPACE_MAP_DEVICE_RANGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_DEVICE_RANGE;
pub const KERNITE_INV_VSPACE_PROTECT: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_PROTECT;
pub const KERNITE_INV_VSPACE_PROTECT_RANGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_PROTECT_RANGE;
pub const KERNITE_INV_VSPACE_MAP_DEMAND: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_DEMAND;
pub const KERNITE_INV_VSPACE_MAP_DEMAND_RANGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_DEMAND_RANGE;
pub const KERNITE_INV_VSPACE_SET_COW_POOL: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_SET_COW_POOL;
pub const KERNITE_INV_VSPACE_REPLENISH_COW_POOL: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_REPLENISH_COW_POOL;
pub const KERNITE_INV_VSPACE_MAP_MO: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_MAP_MO;
pub const KERNITE_INV_VSPACE_SHARE_RO_PAGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_SHARE_RO_PAGE;
pub const KERNITE_INV_VSPACE_FORK_RANGE: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_FORK_RANGE;
pub const KERNITE_INV_VSPACE_UNDO_FORK_RANGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_UNDO_FORK_RANGE;
pub const KERNITE_INV_VSPACE_GET_MEM_STATS: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_GET_MEM_STATS;
pub const KERNITE_INV_VSPACE_GET_RANGE_STATS: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_GET_RANGE_STATS;
pub const KERNITE_INV_VSPACE_GET_TRACE_ID: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_GET_TRACE_ID;
pub const KERNITE_INV_VSPACE_FUTEX_WAIT: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_FUTEX_WAIT;
pub const KERNITE_INV_VSPACE_FUTEX_WAKE: u64 = kernite_bindgen_u64_KERNITE_INV_VSPACE_FUTEX_WAKE;
pub const KERNITE_INV_VSPACE_FUTEX_REQUEUE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_FUTEX_REQUEUE;
pub const KERNITE_INV_VSPACE_RESOLVE_PAGE: u64 =
    kernite_bindgen_u64_KERNITE_INV_VSPACE_RESOLVE_PAGE;
pub const KERNITE_INV_SC_CONFIGURE: u64 = kernite_bindgen_u64_KERNITE_INV_SC_CONFIGURE;
pub const KERNITE_INV_SC_BIND: u64 = kernite_bindgen_u64_KERNITE_INV_SC_BIND;
pub const KERNITE_INV_IOPORT_READ_8: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_READ_8;
pub const KERNITE_INV_IOPORT_READ_16: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_READ_16;
pub const KERNITE_INV_IOPORT_READ_32: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_READ_32;
pub const KERNITE_INV_IOPORT_WRITE_8: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_WRITE_8;
pub const KERNITE_INV_IOPORT_WRITE_16: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_WRITE_16;
pub const KERNITE_INV_IOPORT_WRITE_32: u64 = kernite_bindgen_u64_KERNITE_INV_IOPORT_WRITE_32;
pub const KERNITE_INV_IRQ_BIND_EQ: u64 = kernite_bindgen_u64_KERNITE_INV_IRQ_BIND_EQ;
pub const KERNITE_INV_IRQ_UNBIND_EQ: u64 = kernite_bindgen_u64_KERNITE_INV_IRQ_UNBIND_EQ;
pub const KERNITE_INV_IRQ_ACK: u64 = kernite_bindgen_u64_KERNITE_INV_IRQ_ACK;
pub const KERNITE_INV_MO_COMMIT: u64 = kernite_bindgen_u64_KERNITE_INV_MO_COMMIT;
pub const KERNITE_INV_MO_DECOMMIT: u64 = kernite_bindgen_u64_KERNITE_INV_MO_DECOMMIT;
pub const KERNITE_INV_MO_GET_SIZE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_GET_SIZE;
pub const KERNITE_INV_MO_CLONE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_CLONE;
pub const KERNITE_INV_MO_RESIZE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_RESIZE;
pub const KERNITE_INV_MO_READ: u64 = kernite_bindgen_u64_KERNITE_INV_MO_READ;
pub const KERNITE_INV_MO_WRITE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_WRITE;
pub const KERNITE_INV_MO_HAS_PAGE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_HAS_PAGE;
pub const KERNITE_INV_MO_GET_MAP_COUNT: u64 = kernite_bindgen_u64_KERNITE_INV_MO_GET_MAP_COUNT;
pub const KERNITE_INV_MO_UPDATE_PAGE_FLAGS: u64 =
    kernite_bindgen_u64_KERNITE_INV_MO_UPDATE_PAGE_FLAGS;
pub const KERNITE_INV_MO_ATTACH_PAGER: u64 = kernite_bindgen_u64_KERNITE_INV_MO_ATTACH_PAGER;
pub const KERNITE_INV_MO_SNAPSHOT: u64 = kernite_bindgen_u64_KERNITE_INV_MO_SNAPSHOT;
pub const KERNITE_INV_MO_CLONE_RANGE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_CLONE_RANGE;
pub const KERNITE_INV_MO_MARK_EXECUTABLE: u64 = kernite_bindgen_u64_KERNITE_INV_MO_MARK_EXECUTABLE;
pub const KERNITE_INV_MO_POPULATE_BORROWED: u64 =
    kernite_bindgen_u64_KERNITE_INV_MO_POPULATE_BORROWED;
pub const KERNITE_INV_EQ_WAIT: u64 = kernite_bindgen_u64_KERNITE_INV_EQ_WAIT;
pub const KERNITE_INV_EQ_POLL: u64 = kernite_bindgen_u64_KERNITE_INV_EQ_POLL;
pub const KERNITE_INV_EQ_CANCEL: u64 = kernite_bindgen_u64_KERNITE_INV_EQ_CANCEL;
pub const KERNITE_INV_WATCH_REGISTER: u64 = kernite_bindgen_u64_KERNITE_INV_WATCH_REGISTER;
pub const KERNITE_INV_WATCH_DISARM: u64 = kernite_bindgen_u64_KERNITE_INV_WATCH_DISARM;
pub const KERNITE_INV_WATCH_CANCEL: u64 = kernite_bindgen_u64_KERNITE_INV_WATCH_CANCEL;
pub const KERNITE_INV_MP_WRITE: u64 = kernite_bindgen_u64_KERNITE_INV_MP_WRITE;
pub const KERNITE_INV_MP_READ: u64 = kernite_bindgen_u64_KERNITE_INV_MP_READ;
pub const KERNITE_INV_MP_CLOSE: u64 = kernite_bindgen_u64_KERNITE_INV_MP_CLOSE;
pub const KERNITE_INV_MP_CALL: u64 = kernite_bindgen_u64_KERNITE_INV_MP_CALL;
pub const KERNITE_INV_DP_PRODUCE: u64 = kernite_bindgen_u64_KERNITE_INV_DP_PRODUCE;
pub const KERNITE_INV_DP_CONSUME: u64 = kernite_bindgen_u64_KERNITE_INV_DP_CONSUME;
pub const KERNITE_INV_DP_QUERY: u64 = kernite_bindgen_u64_KERNITE_INV_DP_QUERY;
pub const KERNITE_INV_DP_CLOSE: u64 = kernite_bindgen_u64_KERNITE_INV_DP_CLOSE;
pub const KERNITE_INV_DP_SET_RX_THRESHOLD: u64 =
    kernite_bindgen_u64_KERNITE_INV_DP_SET_RX_THRESHOLD;
pub const KERNITE_INV_DP_SET_TX_THRESHOLD: u64 =
    kernite_bindgen_u64_KERNITE_INV_DP_SET_TX_THRESHOLD;
pub const KERNITE_INV_DP_SHUTDOWN: u64 = kernite_bindgen_u64_KERNITE_INV_DP_SHUTDOWN;
pub const KERNITE_INV_MP_CORE_PAIR: u64 = kernite_bindgen_u64_KERNITE_INV_MP_CORE_PAIR;
pub const KERNITE_INV_DP_CORE_PAIR: u64 = kernite_bindgen_u64_KERNITE_INV_DP_CORE_PAIR;
pub const KERNITE_INV_TIMER_SET: u64 = kernite_bindgen_u64_KERNITE_INV_TIMER_SET;
pub const KERNITE_INV_TIMER_CANCEL: u64 = kernite_bindgen_u64_KERNITE_INV_TIMER_CANCEL;
pub const KERNITE_INV_TIMER_QUERY: u64 = kernite_bindgen_u64_KERNITE_INV_TIMER_QUERY;
pub const KERNITE_INV_RNG_READ: u64 = kernite_bindgen_u64_KERNITE_INV_RNG_READ;
pub const KERNITE_INV_SYSTEM_SHUTDOWN: u64 = kernite_bindgen_u64_KERNITE_INV_SYSTEM_SHUTDOWN;
pub const KERNITE_INV_SYSTEM_REBOOT: u64 = kernite_bindgen_u64_KERNITE_INV_SYSTEM_REBOOT;
pub const KERNITE_INV_CLOCK_READ: u64 = kernite_bindgen_u64_KERNITE_INV_CLOCK_READ;
pub const KERNITE_CLOCK_ID_REALTIME: u64 = kernite_bindgen_u64_KERNITE_CLOCK_ID_REALTIME;
pub const KERNITE_CLOCK_ID_MONOTONIC: u64 = kernite_bindgen_u64_KERNITE_CLOCK_ID_MONOTONIC;
pub const KERNITE_INV_SYSINFO_GET_INFO: u64 = kernite_bindgen_u64_KERNITE_INV_SYSINFO_GET_INFO;
pub const KERNITE_INV_SYSINFO_GET_MEMINFO: u64 =
    kernite_bindgen_u64_KERNITE_INV_SYSINFO_GET_MEMINFO;
pub const KERNITE_INV_KDEBUG_PUTCHAR: u64 = kernite_bindgen_u64_KERNITE_INV_KDEBUG_PUTCHAR;
pub const KERNITE_INV_KDEBUG_PUTSTR: u64 = kernite_bindgen_u64_KERNITE_INV_KDEBUG_PUTSTR;
pub const KERNITE_INV_KDEBUG_PUTBUF: u64 = kernite_bindgen_u64_KERNITE_INV_KDEBUG_PUTBUF;
pub const KERNITE_INV_KDEBUG_DUMP_STATE: u64 = kernite_bindgen_u64_KERNITE_INV_KDEBUG_DUMP_STATE;
pub const KERNITE_INV_KDEBUG_CONSOLE_CONTROL: u64 =
    kernite_bindgen_u64_KERNITE_INV_KDEBUG_CONSOLE_CONTROL;
pub const KERNITE_INV_PAGER_BIND_EQ: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_BIND_EQ;
pub const KERNITE_INV_PAGER_SUPPLY_PAGE: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_SUPPLY_PAGE;
pub const KERNITE_INV_PAGER_FAIL: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_FAIL;
pub const KERNITE_INV_PAGER_DETACH: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_DETACH;
pub const KERNITE_INV_PAGER_BEGIN_WRITEBACK: u64 =
    kernite_bindgen_u64_KERNITE_INV_PAGER_BEGIN_WRITEBACK;
pub const KERNITE_INV_PAGER_WRITEBACK_DONE: u64 =
    kernite_bindgen_u64_KERNITE_INV_PAGER_WRITEBACK_DONE;
pub const KERNITE_INV_PAGER_EVICT_PAGE: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_EVICT_PAGE;
pub const KERNITE_INV_PAGER_SUPPLY_COPY: u64 = kernite_bindgen_u64_KERNITE_INV_PAGER_SUPPLY_COPY;
pub const KERNITE_INV_DEVICE_CONTROL_CREATE_IOPORT: u64 =
    kernite_bindgen_u64_KERNITE_INV_DEVICE_CONTROL_CREATE_IOPORT;
pub const KERNITE_INV_DEVICE_CONTROL_CREATE_DEVICE_UNTYPED: u64 =
    kernite_bindgen_u64_KERNITE_INV_DEVICE_CONTROL_CREATE_DEVICE_UNTYPED;
pub const KERNITE_INV_DEVICE_CONTROL_CREATE_IRQ_HANDLER: u64 =
    kernite_bindgen_u64_KERNITE_INV_DEVICE_CONTROL_CREATE_IRQ_HANDLER;
pub const KERNITE_REGION_KIND_NONE: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_NONE;
pub const KERNITE_REGION_KIND_IMAGE_TEXT: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_IMAGE_TEXT;
pub const KERNITE_REGION_KIND_IMAGE_DATA: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_IMAGE_DATA;
pub const KERNITE_REGION_KIND_IMAGE_BSS: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_IMAGE_BSS;
pub const KERNITE_REGION_KIND_HEAP: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_HEAP;
pub const KERNITE_REGION_KIND_STACK: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_STACK;
pub const KERNITE_REGION_KIND_MMAP: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_MMAP;
pub const KERNITE_REGION_KIND_SHARED_LIB: u64 = kernite_bindgen_u64_KERNITE_REGION_KIND_SHARED_LIB;
pub const KERNITE_PAGE_FLAG_NONE: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_NONE;
pub const KERNITE_PAGE_FLAG_WRITABLE: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_WRITABLE;
pub const KERNITE_PAGE_FLAG_USER: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_USER;
pub const KERNITE_PAGE_FLAG_EXECUTABLE: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_EXECUTABLE;
pub const KERNITE_PAGE_FLAG_COW: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_COW;
pub const KERNITE_PAGE_FLAG_DEMAND: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_DEMAND;
pub const KERNITE_PAGE_FLAG_NOCACHE: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_NOCACHE;
pub const KERNITE_VSPACE_MAP_MO_FLAG_DEMAND: u64 =
    kernite_bindgen_u64_KERNITE_VSPACE_MAP_MO_FLAG_DEMAND;
pub const KERNITE_PAGE_FLAG_WRITETHROUGH: u64 = kernite_bindgen_u64_KERNITE_PAGE_FLAG_WRITETHROUGH;
pub const KERNITE_STATE_NONE: u64 = kernite_bindgen_u64_KERNITE_STATE_NONE;
pub const KERNITE_STATE_READABLE: u64 = kernite_bindgen_u64_KERNITE_STATE_READABLE;
pub const KERNITE_STATE_WRITABLE: u64 = kernite_bindgen_u64_KERNITE_STATE_WRITABLE;
pub const KERNITE_STATE_PEER_CLOSED: u64 = kernite_bindgen_u64_KERNITE_STATE_PEER_CLOSED;
pub const KERNITE_STATE_CLOSED: u64 = kernite_bindgen_u64_KERNITE_STATE_CLOSED;
pub const KERNITE_STATE_ERROR: u64 = kernite_bindgen_u64_KERNITE_STATE_ERROR;
pub const KERNITE_STATE_HANGUP: u64 = kernite_bindgen_u64_KERNITE_STATE_HANGUP;
pub const KERNITE_STATE_OVERRUN: u64 = kernite_bindgen_u64_KERNITE_STATE_OVERRUN;
pub const KERNITE_STATE_SIGNALED: u64 = kernite_bindgen_u64_KERNITE_STATE_SIGNALED;
pub const KERNITE_STATE_TIMED_OUT: u64 = kernite_bindgen_u64_KERNITE_STATE_TIMED_OUT;
pub const KERNITE_STATE_READ_THRESHOLD: u64 = kernite_bindgen_u64_KERNITE_STATE_READ_THRESHOLD;
pub const KERNITE_STATE_WRITE_THRESHOLD: u64 = kernite_bindgen_u64_KERNITE_STATE_WRITE_THRESHOLD;
pub const KERNITE_MP_FLAG_NONE: u64 = kernite_bindgen_u64_KERNITE_MP_FLAG_NONE;
pub const KERNITE_MP_FLAG_CALL: u64 = kernite_bindgen_u64_KERNITE_MP_FLAG_CALL;
pub const KERNITE_MP_FLAG_REPLY: u64 = kernite_bindgen_u64_KERNITE_MP_FLAG_REPLY;
pub const KERNITE_MP_FLAG_FAULT: u64 = kernite_bindgen_u64_KERNITE_MP_FLAG_FAULT;
pub const KERNITE_MP_TXID_KERNEL_BIT_SHIFT: u64 =
    kernite_bindgen_u64_KERNITE_MP_TXID_KERNEL_BIT_SHIFT;
pub const KERNITE_FAULT_NONE: u64 = kernite_bindgen_u64_KERNITE_FAULT_NONE;
pub const KERNITE_FAULT_PAGE_FAULT: u64 = kernite_bindgen_u64_KERNITE_FAULT_PAGE_FAULT;
pub const KERNITE_FAULT_ILLEGAL_INSTRUCTION: u64 =
    kernite_bindgen_u64_KERNITE_FAULT_ILLEGAL_INSTRUCTION;
pub const KERNITE_FAULT_BREAKPOINT: u64 = kernite_bindgen_u64_KERNITE_FAULT_BREAKPOINT;
pub const KERNITE_FAULT_USER_EXCEPTION: u64 = kernite_bindgen_u64_KERNITE_FAULT_USER_EXCEPTION;
pub const KERNITE_FAULT_OOM: u64 = kernite_bindgen_u64_KERNITE_FAULT_OOM;
pub const KERNITE_FAULT_CAP: u64 = kernite_bindgen_u64_KERNITE_FAULT_CAP;
pub const KERNITE_BOOTINFO_MAGIC: u64 = kernite_bindgen_u64_KERNITE_BOOTINFO_MAGIC;
pub const KERNITE_BOOTINFO_VADDR: u64 = kernite_bindgen_u64_KERNITE_BOOTINFO_VADDR;
