/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Bindgen-only wrapper for kernite UAPI.
 *
 * The public headers under kernite/include/uapi stay C/asm-facing ABI
 * source. Bindgen narrows small ULL macros to u32, so constants that are
 * carried in syscall registers or other u64 wire words are re-exposed here
 * as typed uint64_t values while preserving the public C macro surface.
 */

#ifndef KERNITE_UAPI_BINDGEN_H
#define KERNITE_UAPI_BINDGEN_H

#include "kernite.h"

#define KERNITE_BINDGEN_WORD_CONSTANTS(X)                                      \
    X(KERNITE_ABI_VERSION)                                                     \
    X(KERNITE_SYS_INVOKE)                                                      \
    X(KERNITE_OK)                                                              \
    X(KERNITE_ERR_INVALID_CAPABILITY)                                          \
    X(KERNITE_ERR_INVALID_OPERATION)                                           \
    X(KERNITE_ERR_INSUFFICIENT_RIGHTS)                                         \
    X(KERNITE_ERR_INVALID_ARGUMENT)                                            \
    X(KERNITE_ERR_OUT_OF_MEMORY)                                               \
    X(KERNITE_ERR_NOT_FOUND)                                                   \
    X(KERNITE_ERR_BUSY)                                                        \
    X(KERNITE_ERR_ALREADY_EXISTS)                                              \
    X(KERNITE_ERR_WOULD_BLOCK)                                                 \
    X(KERNITE_ERR_BAD_ADDRESS)                                                 \
    X(KERNITE_ERR_OUT_OF_RANGE)                                                \
    X(KERNITE_ERR_CANCELLED)                                                   \
    X(KERNITE_ERR_RESTART)                                                     \
    X(KERNITE_ERR_DEADLOCK)                                                    \
    X(KERNITE_ERR_INTERRUPTED)                                                 \
    X(KERNITE_ERR_TOO_LARGE)                                                   \
    X(KERNITE_ERR_NOT_SUPPORTED)                                               \
    X(KERNITE_ERR_READONLY)                                                    \
    X(KERNITE_ERR_SLOT_OCCUPIED)                                               \
    X(KERNITE_ERR_ALREADY_MAPPED)                                              \
    X(KERNITE_ERR_PEER_CLOSED)                                                 \
    X(KERNITE_ERR_QUEUE_OVERFLOW)                                              \
    X(KERNITE_ERR_WATCH_CANCELLED)                                             \
    X(KERNITE_ERR_ABI_MISMATCH)                                                \
    X(KERNITE_ERR_IO_ERROR)                                                    \
    X(KERNITE_ERR_TIMED_OUT)                                                   \
    X(KERNITE_ERR_PENDING)                                                     \
    X(KERNITE_ERR_INSUFFICIENT_RESOURCES)                                      \
    X(KERNITE_OBJ_NULL)                                                        \
    X(KERNITE_OBJ_UNTYPED)                                                     \
    X(KERNITE_OBJ_TCB)                                                         \
    X(KERNITE_OBJ_CNODE)                                                       \
    X(KERNITE_OBJ_VSPACE)                                                      \
    X(KERNITE_OBJ_FRAME)                                                       \
    X(KERNITE_OBJ_IRQ_HANDLER)                                                 \
    X(KERNITE_OBJ_IO_PORT)                                                     \
    X(KERNITE_OBJ_SCHED_CONTEXT)                                               \
    X(KERNITE_OBJ_MEMORY_OBJECT)                                               \
    X(KERNITE_OBJ_EVENT_QUEUE)                                                 \
    X(KERNITE_OBJ_WATCH)                                                       \
    X(KERNITE_OBJ_MESSAGE_PIPE)                                                \
    X(KERNITE_OBJ_DATA_PIPE)                                                   \
    X(KERNITE_OBJ_TIMER)                                                       \
    X(KERNITE_OBJ_KERNEL_RNG)                                                  \
    X(KERNITE_OBJ_SYSTEM_CONTROL)                                              \
    X(KERNITE_OBJ_CLOCK)                                                       \
    X(KERNITE_OBJ_SYSTEM_INFO)                                                 \
    X(KERNITE_OBJ_KERNEL_DEBUG)                                                \
    X(KERNITE_OBJ_MESSAGE_PIPE_CORE)                                           \
    X(KERNITE_OBJ_DATA_PIPE_CORE)                                              \
    X(KERNITE_OBJ_PAGER)                                                       \
    X(KERNITE_OBJ_DEVICE_CONTROL)                                              \
    X(KERNITE_OBJ_VM_HIERARCHY_STATE)                                          \
    X(KERNITE_OBJ_EXEC_AUTHORITY)                                              \
    X(KERNITE_OBJ_PAGE_TABLE)                                                  \
    X(KERNITE_PAGE_BYTES)                                                      \
    X(KERNITE_PAGE_TABLE_BYTES)                                                \
    X(KERNITE_CNODE_DEFAULT_SIZE_BITS)                                         \
    X(KERNITE_CNODE_MIN_SIZE_BITS)                                             \
    X(KERNITE_CNODE_MAX_SIZE_BITS)                                             \
    X(KERNITE_CNODE_HEADER_BYTES)                                              \
    X(KERNITE_CNODE_SLOT_BYTES)                                                \
    X(KERNITE_VSPACE_TRACKING_BYTES)                                           \
    X(KERNITE_VSPACE_BYTES)                                                    \
    X(KERNITE_MO_HEADER_BYTES)                                                 \
    X(KERNITE_TCB_BYTES)                                                       \
    X(KERNITE_SCHED_CONTEXT_BYTES)                                             \
    X(KERNITE_IRQ_HANDLER_BYTES)                                               \
    X(KERNITE_IO_PORT_BYTES)                                                   \
    X(KERNITE_EVENT_QUEUE_BYTES)                                               \
    X(KERNITE_WATCH_BYTES)                                                     \
    X(KERNITE_MESSAGE_PIPE_BYTES)                                              \
    X(KERNITE_MESSAGE_PIPE_CORE_BYTES)                                         \
    X(KERNITE_DATA_PIPE_BYTES)                                                 \
    X(KERNITE_DATA_PIPE_CORE_BYTES)                                            \
    X(KERNITE_TIMER_BYTES)                                                     \
    X(KERNITE_KERNEL_RNG_BYTES)                                                \
    X(KERNITE_SYSTEM_CONTROL_BYTES)                                            \
    X(KERNITE_CLOCK_BYTES)                                                     \
    X(KERNITE_SYSTEM_INFO_BYTES)                                               \
    X(KERNITE_KERNEL_DEBUG_BYTES)                                              \
    X(KERNITE_PAGER_BYTES)                                                     \
    X(KERNITE_DEVICE_CONTROL_BYTES)                                            \
    X(KERNITE_VM_HIERARCHY_STATE_BYTES)                                        \
    X(KERNITE_EXEC_AUTHORITY_BYTES)                                            \
    X(KERNITE_CAP_SELF_TCB)                                                    \
    X(KERNITE_CAP_SELF_VSPACE)                                                 \
    X(KERNITE_CAP_SELF_CSPACE)                                                 \
    X(KERNITE_INV_CNODE_COPY)                                                  \
    X(KERNITE_INV_CNODE_MINT)                                                  \
    X(KERNITE_INV_CNODE_MOVE)                                                  \
    X(KERNITE_INV_CNODE_MUTATE)                                                \
    X(KERNITE_INV_CNODE_DELETE)                                                \
    X(KERNITE_INV_CNODE_REVOKE)                                                \
    X(KERNITE_INV_CNODE_SET_GUARD)                                             \
    X(KERNITE_INV_CNODE_GET_INFO)                                              \
    X(KERNITE_INV_UNTYPED_RETYPE)                                              \
    X(KERNITE_INV_UNTYPED_RESET)                                               \
    X(KERNITE_INV_UNTYPED_GET_STATS)                                           \
    X(KERNITE_INV_TCB_CONFIGURE)                                               \
    X(KERNITE_INV_TCB_START)                                                   \
    X(KERNITE_INV_TCB_STOP)                                                    \
    X(KERNITE_INV_TCB_KILL)                                                    \
    X(KERNITE_INV_TCB_YIELD)                                                   \
    X(KERNITE_INV_TCB_GET_STATE)                                               \
    X(KERNITE_INV_TCB_GET_ABI_VERSION)                                         \
    X(KERNITE_INV_TCB_SET_INVOKE_DEPTHS)                                       \
    X(KERNITE_INV_TCB_SET_SPACE)                                               \
    X(KERNITE_INV_TCB_SET_AFFINITY)                                            \
    X(KERNITE_INV_TCB_READ_REGISTERS)                                          \
    X(KERNITE_INV_TCB_WRITE_REGISTERS)                                         \
    X(KERNITE_INV_TCB_SET_PRIORITY)                                            \
    X(KERNITE_INV_TCB_SET_IPC_BUFFER)                                          \
    X(KERNITE_INV_TCB_SET_FAULT_PIPE)                                          \
    X(KERNITE_INV_TCB_COPY_FPU)                                                \
    X(KERNITE_INV_TCB_SET_TLS_BASE)                                            \
    X(KERNITE_INV_TCB_SET_STACK_BOUNDS)                                        \
    X(KERNITE_INV_TCB_SET_SCHED_CLASS)                                         \
    X(KERNITE_INV_TCB_GET_SPACE_INFO)                                          \
    X(KERNITE_INV_TCB_GET_CPU_TIMES)                                           \
    X(KERNITE_INV_TCB_GET_TRACE_ID)                                            \
    X(KERNITE_INV_TCB_SET_ABI_TP)                                              \
    X(KERNITE_INV_TCB_EXIT_SELF)                                               \
    X(KERNITE_INV_VSPACE_MAP)                                                  \
    X(KERNITE_INV_VSPACE_UNMAP)                                                \
    X(KERNITE_INV_VSPACE_MAP_PT)                                               \
    X(KERNITE_INV_VSPACE_WALK)                                                 \
    X(KERNITE_INV_VSPACE_COPY_PAGE)                                            \
    X(KERNITE_INV_VSPACE_MAP_DEVICE)                                           \
    X(KERNITE_INV_VSPACE_MAP_DEVICE_RANGE)                                     \
    X(KERNITE_INV_VSPACE_PROTECT)                                              \
    X(KERNITE_INV_VSPACE_PROTECT_RANGE)                                        \
    X(KERNITE_INV_VSPACE_MAP_DEMAND)                                           \
    X(KERNITE_INV_VSPACE_MAP_DEMAND_RANGE)                                     \
    X(KERNITE_INV_VSPACE_SET_COW_POOL)                                         \
    X(KERNITE_INV_VSPACE_REPLENISH_COW_POOL)                                   \
    X(KERNITE_INV_VSPACE_MAP_MO)                                               \
    X(KERNITE_INV_VSPACE_SHARE_RO_PAGE)                                        \
    X(KERNITE_INV_VSPACE_FORK_RANGE)                                           \
    X(KERNITE_INV_VSPACE_UNDO_FORK_RANGE)                                      \
    X(KERNITE_INV_VSPACE_GET_MEM_STATS)                                        \
    X(KERNITE_INV_VSPACE_GET_RANGE_STATS)                                      \
    X(KERNITE_INV_VSPACE_GET_TRACE_ID)                                         \
    X(KERNITE_INV_VSPACE_FUTEX_WAIT)                                           \
    X(KERNITE_INV_VSPACE_FUTEX_WAKE)                                           \
    X(KERNITE_INV_VSPACE_FUTEX_REQUEUE)                                        \
    X(KERNITE_INV_VSPACE_RESOLVE_PAGE)                                         \
    X(KERNITE_INV_SC_CONFIGURE)                                                \
    X(KERNITE_INV_SC_BIND)                                                     \
    X(KERNITE_INV_IOPORT_READ_8)                                               \
    X(KERNITE_INV_IOPORT_READ_16)                                              \
    X(KERNITE_INV_IOPORT_READ_32)                                              \
    X(KERNITE_INV_IOPORT_WRITE_8)                                              \
    X(KERNITE_INV_IOPORT_WRITE_16)                                             \
    X(KERNITE_INV_IOPORT_WRITE_32)                                             \
    X(KERNITE_INV_IRQ_BIND_EQ)                                                 \
    X(KERNITE_INV_IRQ_UNBIND_EQ)                                               \
    X(KERNITE_INV_IRQ_ACK)                                                     \
    X(KERNITE_INV_MO_COMMIT)                                                   \
    X(KERNITE_INV_MO_DECOMMIT)                                                 \
    X(KERNITE_INV_MO_GET_SIZE)                                                 \
    X(KERNITE_INV_MO_CLONE)                                                    \
    X(KERNITE_INV_MO_RESIZE)                                                   \
    X(KERNITE_INV_MO_READ)                                                     \
    X(KERNITE_INV_MO_WRITE)                                                    \
    X(KERNITE_INV_MO_HAS_PAGE)                                                 \
    X(KERNITE_INV_MO_GET_MAP_COUNT)                                            \
    X(KERNITE_INV_MO_UPDATE_PAGE_FLAGS)                                        \
    X(KERNITE_INV_MO_ATTACH_PAGER)                                             \
    X(KERNITE_INV_MO_SNAPSHOT)                                                 \
    X(KERNITE_INV_MO_CLONE_RANGE)                                              \
    X(KERNITE_INV_MO_MARK_EXECUTABLE)                                          \
    X(KERNITE_INV_MO_POPULATE_BORROWED)                                        \
    X(KERNITE_INV_EQ_WAIT)                                                     \
    X(KERNITE_INV_EQ_POLL)                                                     \
    X(KERNITE_INV_EQ_CANCEL)                                                   \
    X(KERNITE_INV_WATCH_REGISTER)                                              \
    X(KERNITE_INV_WATCH_DISARM)                                                \
    X(KERNITE_INV_WATCH_CANCEL)                                                \
    X(KERNITE_INV_MP_WRITE)                                                    \
    X(KERNITE_INV_MP_READ)                                                     \
    X(KERNITE_INV_MP_CLOSE)                                                    \
    X(KERNITE_INV_MP_CALL)                                                     \
    X(KERNITE_INV_DP_PRODUCE)                                                  \
    X(KERNITE_INV_DP_CONSUME)                                                  \
    X(KERNITE_INV_DP_QUERY)                                                    \
    X(KERNITE_INV_DP_CLOSE)                                                    \
    X(KERNITE_INV_DP_SET_RX_THRESHOLD)                                         \
    X(KERNITE_INV_DP_SET_TX_THRESHOLD)                                         \
    X(KERNITE_INV_DP_SHUTDOWN)                                                 \
    X(KERNITE_INV_MP_CORE_PAIR)                                                \
    X(KERNITE_INV_DP_CORE_PAIR)                                                \
    X(KERNITE_INV_TIMER_SET)                                                   \
    X(KERNITE_INV_TIMER_CANCEL)                                                \
    X(KERNITE_INV_TIMER_QUERY)                                                 \
    X(KERNITE_INV_RNG_READ)                                                    \
    X(KERNITE_INV_SYSTEM_SHUTDOWN)                                             \
    X(KERNITE_INV_SYSTEM_REBOOT)                                               \
    X(KERNITE_INV_CLOCK_READ)                                                  \
    X(KERNITE_CLOCK_ID_REALTIME)                                               \
    X(KERNITE_CLOCK_ID_MONOTONIC)                                              \
    X(KERNITE_INV_SYSINFO_GET_INFO)                                            \
    X(KERNITE_INV_SYSINFO_GET_MEMINFO)                                         \
    X(KERNITE_INV_KDEBUG_PUTCHAR)                                              \
    X(KERNITE_INV_KDEBUG_PUTSTR)                                               \
    X(KERNITE_INV_KDEBUG_PUTBUF)                                               \
    X(KERNITE_INV_KDEBUG_DUMP_STATE)                                           \
    X(KERNITE_INV_KDEBUG_CONSOLE_CONTROL)                                      \
    X(KERNITE_INV_PAGER_BIND_EQ)                                               \
    X(KERNITE_INV_PAGER_SUPPLY_PAGE)                                           \
    X(KERNITE_INV_PAGER_FAIL)                                                  \
    X(KERNITE_INV_PAGER_DETACH)                                                \
    X(KERNITE_INV_PAGER_BEGIN_WRITEBACK)                                       \
    X(KERNITE_INV_PAGER_WRITEBACK_DONE)                                        \
    X(KERNITE_INV_PAGER_EVICT_PAGE)                                            \
    X(KERNITE_INV_PAGER_SUPPLY_COPY)                                           \
    X(KERNITE_INV_DEVICE_CONTROL_CREATE_IOPORT)                                \
    X(KERNITE_INV_DEVICE_CONTROL_CREATE_DEVICE_UNTYPED)                        \
    X(KERNITE_INV_DEVICE_CONTROL_CREATE_IRQ_HANDLER)                           \
    X(KERNITE_REGION_KIND_NONE)                                                \
    X(KERNITE_REGION_KIND_IMAGE_TEXT)                                          \
    X(KERNITE_REGION_KIND_IMAGE_DATA)                                          \
    X(KERNITE_REGION_KIND_IMAGE_BSS)                                           \
    X(KERNITE_REGION_KIND_HEAP)                                                \
    X(KERNITE_REGION_KIND_STACK)                                               \
    X(KERNITE_REGION_KIND_MMAP)                                                \
    X(KERNITE_REGION_KIND_SHARED_LIB)                                          \
    X(KERNITE_PAGE_FLAG_NONE)                                                  \
    X(KERNITE_PAGE_FLAG_WRITABLE)                                              \
    X(KERNITE_PAGE_FLAG_USER)                                                  \
    X(KERNITE_PAGE_FLAG_EXECUTABLE)                                            \
    X(KERNITE_PAGE_FLAG_COW)                                                   \
    X(KERNITE_PAGE_FLAG_DEMAND)                                                \
    X(KERNITE_PAGE_FLAG_NOCACHE)                                               \
    X(KERNITE_VSPACE_MAP_MO_FLAG_DEMAND)                                       \
    X(KERNITE_PAGE_FLAG_WRITETHROUGH)                                          \
    X(KERNITE_STATE_NONE)                                                      \
    X(KERNITE_STATE_READABLE)                                                  \
    X(KERNITE_STATE_WRITABLE)                                                  \
    X(KERNITE_STATE_PEER_CLOSED)                                               \
    X(KERNITE_STATE_CLOSED)                                                    \
    X(KERNITE_STATE_ERROR)                                                     \
    X(KERNITE_STATE_HANGUP)                                                    \
    X(KERNITE_STATE_OVERRUN)                                                   \
    X(KERNITE_STATE_SIGNALED)                                                  \
    X(KERNITE_STATE_TIMED_OUT)                                                 \
    X(KERNITE_STATE_READ_THRESHOLD)                                            \
    X(KERNITE_STATE_WRITE_THRESHOLD)                                           \
    X(KERNITE_MP_FLAG_NONE)                                                    \
    X(KERNITE_MP_FLAG_CALL)                                                    \
    X(KERNITE_MP_FLAG_REPLY)                                                   \
    X(KERNITE_MP_FLAG_FAULT)                                                   \
    X(KERNITE_MP_TXID_KERNEL_BIT_SHIFT)                                        \
    X(KERNITE_FAULT_NONE)                                                      \
    X(KERNITE_FAULT_PAGE_FAULT)                                                \
    X(KERNITE_FAULT_ILLEGAL_INSTRUCTION)                                       \
    X(KERNITE_FAULT_BREAKPOINT)                                                \
    X(KERNITE_FAULT_USER_EXCEPTION)                                            \
    X(KERNITE_FAULT_OOM)                                                       \
    X(KERNITE_FAULT_CAP)                                                       \
    X(KERNITE_BOOTINFO_MAGIC)                                                  \
    X(KERNITE_BOOTINFO_VADDR)

#define KERNITE_BINDGEN_CAPTURE_U64(name)                                     \
    static const uint64_t kernite_bindgen_u64_##name = name;
KERNITE_BINDGEN_WORD_CONSTANTS(KERNITE_BINDGEN_CAPTURE_U64)
#undef KERNITE_BINDGEN_CAPTURE_U64
#undef KERNITE_BINDGEN_WORD_CONSTANTS

#endif /* KERNITE_UAPI_BINDGEN_H */
