[package]
name = "saltyos-bootloader-uefi"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
uefi = "0.26"
uefi-services = "0.23"
saltyos-ska = { path = "../../abi/ska" }
saltyos-bootloader-common = { path = "../common" }
x86_64 = "0.15"

[package.metadata.cargo-uefi]
parent-package = "saltyos-bootloader-uefi"
