//! Cross-compile environment configuration
//! SPDX-License-Identifier: GPL-2.0-only

use std::path::{Path, PathBuf};

pub struct BuildEnv {
    pub cc: String,
    pub cxx: String,
    pub cflags: String,
    pub ldflags: String,
    pub libs: String,
    pub ar: String,
    pub ranlib: String,
    pub strip: String,
    pub rustc: String,
    pub cargo: String,
    pub autotools_host: String,
    pub salty_host: String,
    pub salty_inc: PathBuf,
    pub sysroot_dir: PathBuf,
    pub toolchain_prefix: PathBuf,
    pub build_root: PathBuf,
    pub arch: String,
    pub nproc: usize,
    pub verbose: bool,
}

impl BuildEnv {
    pub fn new(build_dir: &Path, _port_dir: &Path, jobs: usize, verbose: bool) -> Self {
        let build_root = if build_dir.is_absolute() {
            build_dir.to_path_buf()
        } else {
            std::env::current_dir().unwrap().join(build_dir)
        };

        // Sysroot: generated by `just sysroot` into <build>/sysroot
        let sysroot_dir = build_root.join("sysroot");

        // basaltc include path: <sysroot>/usr/include (after `just sysroot`)
        let salty_inc = sysroot_dir.join("usr").join("include");

        // Resolve the SaltyOS clang: prefer SALTYOS_TOOLCHAIN_PREFIX env var,
        // then derive from build_root (../../build-toolchain/prefix).
        // Falls back to system clang if the custom binary is not found.
        let toolchain_prefix = std::env::var("SALTYOS_TOOLCHAIN_PREFIX")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                build_root
                    .parent()
                    .unwrap_or(&build_root)
                    .join("build-toolchain")
                    .join("prefix")
            });

        let cc = {
            let cc_path = toolchain_prefix.join("bin").join("clang");
            if cc_path.is_file() {
                cc_path.to_string_lossy().into_owned()
            } else {
                "clang".to_string()
            }
        };

        let cxx = {
            let cxx_path = toolchain_prefix.join("bin").join("clang++");
            if cxx_path.is_file() {
                cxx_path.to_string_lossy().into_owned()
            } else {
                "clang++".to_string()
            }
        };

        // Detect target architecture from SALTYOS_ARCH env or build dir name.
        let arch = std::env::var("SALTYOS_ARCH").unwrap_or_else(|_| {
            let dir_name = build_dir.file_name().unwrap_or_default().to_string_lossy();
            if dir_name.contains("aarch64") { "aarch64".to_string() }
            else { "x86_64".to_string() }
        });
        let target_triple = format!("{arch}-unknown-saltyos");

        // CFLAGS: the driver auto-injects system includes from the sysroot.
        // -fno-builtin omitted: autotools needs builtin recognition for function checks.
        let cflags = format!(
            "-fno-stack-protector -fPIC \
             --target={target_triple} \
             --sysroot={sysroot}",
            sysroot = sysroot_dir.display(),
        );

        // LDFLAGS: the driver auto-injects crt_start.o, -lc, -ltrona, core.o,
        // compiler_builtins.o, and the PIE linker script from the sysroot.
        let ldflags = format!(
            "--target={target_triple} \
             --sysroot={sysroot}",
            sysroot = sysroot_dir.display(),
        );

        // LIBS is empty: CRT objects and runtime libs are injected by the driver.
        let libs = String::new();

        let rustc = {
            let rustc_path = toolchain_prefix.join("bin").join("rustc");
            if rustc_path.is_file() {
                rustc_path.to_string_lossy().into_owned()
            } else {
                "rustc".to_string()
            }
        };

        let cargo = {
            let cargo_path = toolchain_prefix.join("bin").join("cargo");
            if cargo_path.is_file() {
                cargo_path.to_string_lossy().into_owned()
            } else {
                "cargo".to_string()
            }
        };

        BuildEnv {
            cc,
            cxx,
            cflags,
            ldflags,
            libs,
            ar: "llvm-ar".to_string(),
            ranlib: "llvm-ranlib".to_string(),
            strip: "llvm-strip".to_string(),
            rustc,
            cargo,
            autotools_host: target_triple.clone(),
            salty_host: target_triple,
            salty_inc,
            sysroot_dir,
            toolchain_prefix,
            build_root,
            arch,
            nproc: jobs,
            verbose,
        }
    }
}
