//! Cross-compile environment configuration
//! SPDX-License-Identifier: GPL-2.0-only

use std::path::{Path, PathBuf};

pub struct BuildEnv {
    pub cc: String,
    pub cxx: String,
    pub cflags: String,
    pub ldflags: String,
    pub libs: String,
    pub ar: String,
    pub ranlib: String,
    pub strip: String,
    pub autotools_host: String,
    pub salty_host: String,
    pub salty_inc: PathBuf,
    pub sysroot_dir: PathBuf,
    pub toolchain_prefix: PathBuf,
    pub build_root: PathBuf,
    pub nproc: usize,
    pub verbose: bool,
}

impl BuildEnv {
    pub fn new(build_dir: &Path, _port_dir: &Path, jobs: usize, verbose: bool) -> Self {
        let build_root = if build_dir.is_absolute() {
            build_dir.to_path_buf()
        } else {
            std::env::current_dir().unwrap().join(build_dir)
        };

        // Sysroot: generated by `just sysroot` into <build>/sysroot
        let sysroot_dir = build_root.join("sysroot");

        // besalt-c include path: <sysroot>/usr/include (after `just sysroot`)
        let salty_inc = sysroot_dir.join("usr").join("include");

        // Resolve the SaltyOS clang: prefer SALTYOS_TOOLCHAIN_PREFIX env var,
        // then derive from build_root (../../build-toolchain/prefix).
        // Falls back to system clang if the custom binary is not found.
        let toolchain_prefix = std::env::var("SALTYOS_TOOLCHAIN_PREFIX")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                build_root
                    .parent()
                    .unwrap_or(&build_root)
                    .join("build-toolchain")
                    .join("prefix")
            });

        let cc = {
            let cc_path = toolchain_prefix.join("bin").join("clang");
            if cc_path.is_file() {
                cc_path.to_string_lossy().into_owned()
            } else {
                "clang".to_string()
            }
        };

        let cxx = {
            let cxx_path = toolchain_prefix.join("bin").join("clang++");
            if cxx_path.is_file() {
                cxx_path.to_string_lossy().into_owned()
            } else {
                "clang++".to_string()
            }
        };

        // CFLAGS: the driver auto-injects system includes from the sysroot.
        // -fno-builtin omitted: autotools needs builtin recognition for function checks.
        // -fPIC is implied by --target=x86_64-unknown-saltyos.
        let cflags = format!(
            "-fno-stack-protector \
             --target=x86_64-unknown-saltyos \
             --sysroot={sysroot}",
            sysroot = sysroot_dir.display(),
        );

        // LDFLAGS: the driver auto-injects crt_start.o, -lc, -lbesalt, core.o,
        // compiler_builtins.o, and the PIE linker script from the sysroot.
        let ldflags = format!(
            "--target=x86_64-unknown-saltyos \
             --sysroot={sysroot}",
            sysroot = sysroot_dir.display(),
        );

        // LIBS is empty: CRT objects and runtime libs are injected by the driver.
        let libs = String::new();

        BuildEnv {
            cc,
            cxx,
            cflags,
            ldflags,
            libs,
            ar: "llvm-ar".to_string(),
            ranlib: "llvm-ranlib".to_string(),
            strip: "llvm-strip".to_string(),
            autotools_host: "x86_64-unknown-saltyos".to_string(),
            salty_host: "x86_64-unknown-saltyos".to_string(),
            salty_inc,
            sysroot_dir,
            toolchain_prefix,
            build_root,
            nproc: jobs,
            verbose,
        }
    }
}
