# hints/saltyos.sh
# Hints for SaltyOS — capability-based microkernel OS
# Based on linux.sh with SaltyOS-specific adjustments

# No setuid script support
d_suidsafe='undef'

# ELF shared libraries
so='so'
dlext='so'

# Threading: not yet
usethreads='undef'
useithreads='undef'

# Large file support
uselargefiles='define'
use64bitint='define'
use64bitall='define'

# No locale support beyond C/POSIX
d_setlocale='define'
i_fcntl='define'
i_poll='define'
i_dlfcn='define'
ldlibpthname='LD_LIBRARY_PATH'
usensgetexecutablepath='undef'
usekernprocpathname='undef'
i_syssyscall='undef'

# Dynamic loading via dlopen
usedl='define'
d_dlopen='define'
d_dlerror='define'
d_dlsym='define'
d_dlclose='define'
cccdlflags='-fPIC'
ccdlflags=''
lddlflags='-shared'

# Networking
d_socket='define'
d_gethbyname='define'
d_gethbyaddr='undef'
d_getservbyname='define'

# Signal handling
d_sigaction='define'
d_sigsetjmp='define'

# Standard functions available in basaltc
d_access='define'
d_chown='define'
d_chroot='define'
d_closedir='define'
d_crypt='undef'
d_dup2='define'
d_fcntl='define'
d_fork='define'
d_fstat='define'
d_fstatat='define'
d_getcwd='define'
d_getenv='define'
d_geteuid='define'
d_getgid='define'
d_getlogin='define'
d_getpid='define'
d_getuid='define'
d_gmtime_r='define'
d_link='define'
d_localtime_r='define'
d_lstat='define'
d_mkdir='define'
d_mkstemp='define'
d_mktime='define'
d_mmap='define'
d_mprotect='define'
d_munmap='define'
d_open3='define'
d_opendir='define'
d_pipe='define'
d_poll='define'
d_readdir='define'
d_readlink='define'
d_rename='define'
d_rmdir='define'
d_select='define'
d_setenv='define'
d_sigprocmask='define'
d_snprintf='define'
d_stat='define'
d_strchr='define'
d_strerror='define'
d_strlcat='define'
d_strlcpy='define'
d_strtol='define'
d_strtoul='define'
d_symlink='define'
d_time='define'
d_times='undef'
d_truncate='define'
d_umask='define'
d_unlink='define'
d_utime='define'
d_vfork='undef'
d_void_closedir='undef'
d_waitpid='define'

# Functions we do NOT have
d_getprotobyname_r='undef'
d_getprotobynumber_r='undef'
d_getprotoent_r='undef'
d_getpwent='define'
d_getpwent_r='undef'
d_getgrent='define'
d_getgrent_r='undef'
d_getgrgid_r='define'
d_getgrnam_r='define'
d_getpwnam_r='define'
d_getpwuid_r='define'
d_getspent_r='undef'
d_sethostent_r='undef'
d_setlocale_r='undef'
d_setservent_r='undef'
d_setgrps='undef'
d_setregid='undef'
d_setreuid='undef'
d_setrgid='undef'
d_setruid='undef'
d_endgrent='define'
d_endpwent='define'
d_endhostent='undef'
d_endservent='undef'
d_semctl='undef'
d_semget='undef'
d_semop='undef'
d_shmctl='undef'
d_shmget='undef'
d_shmat='undef'
d_shmdt='undef'
d_msg='undef'
d_msgctl='undef'
d_msgget='undef'
d_msgrcv='undef'
d_msgsnd='undef'
d_siginfo_si_band='undef'
d_getprior='undef'
d_setprior='undef'
d_pw_change='undef'
d_pw_class='undef'
d_pw_expire='undef'

# Additional functions verified in the current SaltyOS sysroot/libc
d_poll='define'
d_times='define'

# Paths
prefix='/usr'
bin='/usr/bin'
privlib='/usr/lib/perl5'
archlib='/usr/lib/perl5'
sitelib='/usr/lib/perl5/site'
sitearch='/usr/lib/perl5/site'
