#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate a small manifest for the in-kernel DWARF CFI unwinder."""

from __future__ import annotations

import argparse
import pathlib
import re


def find_eh_frame(sections_text: str) -> tuple[int, int]:
    for line in sections_text.splitlines():
        if ".eh_frame" not in line or ".eh_frame_hdr" in line:
            continue
        # llvm-readelf -S lines include address and size as hex columns.
        parts = line.split()
        hexes = [p for p in parts if re.fullmatch(r"[0-9A-Fa-f]{4,16}", p)]
        if len(hexes) >= 2:
            addr = int(hexes[-4] if len(hexes) >= 4 else hexes[0], 16)
            size = int(hexes[-2] if len(hexes) >= 2 else "0", 16)
            return addr, size
    return 0, 0


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--elf", required=True)
    p.add_argument("--sections", required=True)
    p.add_argument("--output", required=True)
    args = p.parse_args()

    sections = pathlib.Path(args.sections).read_text(errors="replace")
    addr, size = find_eh_frame(sections)

    pathlib.Path(args.output).write_text(
        "\n".join(
            [
                "/* Generated by tools/kernite-unwind.py. */",
                ".section .kernite_unwind,\"a\"",
                ".balign 8",
                ".global __kernite_unwind_manifest_start",
                "__kernite_unwind_manifest_start:",
                f"    .quad 0x{addr:016x}",
                f"    .quad 0x{size:016x}",
                ".global __kernite_unwind_manifest_end",
                "__kernite_unwind_manifest_end:",
                "",
            ]
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
