#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the Kernite build-identity assembly blob."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import subprocess
from collections import OrderedDict


def run_git(source_root: pathlib.Path, *args: str) -> str | None:
    try:
        return subprocess.check_output(
            ["git", "-C", str(source_root), *args],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return None


def sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def asm_string(name: str, value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace('"', '\\"')
    )
    return f".global {name}\n{name}:\n    .asciz \"{escaped}\"\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--source-root", required=True)
    p.add_argument("--arch", required=True)
    p.add_argument("--rustc-version", required=True)
    p.add_argument("--profile", required=True)
    p.add_argument("--kernel-log-level", required=True)
    p.add_argument("--kernel-debug-modules", required=True)
    p.add_argument("--debug-serial", required=True)
    p.add_argument("--debug-symbols", required=True)
    p.add_argument("--max-cpus", required=True)
    p.add_argument("--kernel-stack-size", required=True)
    p.add_argument("--target-json", required=True)
    p.add_argument("--linker-script", required=True)
    p.add_argument("--rust-cfg-list", required=True)
    p.add_argument("--output", required=True)
    args = p.parse_args()

    source_root = pathlib.Path(args.source_root)
    target_json = pathlib.Path(args.target_json)
    linker_script = pathlib.Path(args.linker_script)

    git_rev = run_git(source_root, "rev-parse", "--short=12", "HEAD") or "unknown"
    dirty = run_git(source_root, "diff", "--quiet") is None
    dirty = dirty or run_git(source_root, "diff", "--cached", "--quiet") is None

    cfgs = sorted(c for c in args.rust_cfg_list.split(",") if c)
    cfg_list = ",".join(cfgs)

    canonical = OrderedDict(
        [
            ("arch", args.arch),
            ("rustc_version", args.rustc_version),
            ("kernel_log_level", args.kernel_log_level),
            ("kernel_debug_modules", args.kernel_debug_modules),
            ("debug_serial", args.debug_serial),
            ("debug_symbols", args.debug_symbols),
            ("max_cpus", args.max_cpus),
            ("kernel_stack_size", args.kernel_stack_size),
            ("target_json_sha256", sha256_file(target_json)),
            ("linker_script_sha256", sha256_file(linker_script)),
            ("kernel_rust_cfgs", cfg_list),
        ]
    )
    summary = "".join(f"{k}={v}\n" for k, v in canonical.items())
    config_hash = hashlib.sha256(summary.encode("utf-8")).hexdigest()
    git_display = git_rev + ("-dirty" if dirty else "")

    out = pathlib.Path(args.output)
    out.write_text(
        "\n".join(
            [
                "/* Generated by tools/kernite-build-info.py. */",
                ".section .rodata.kernite_build_info,\"a\"",
                ".balign 8",
                ".global __kernite_build_info_start",
                "__kernite_build_info_start:",
                asm_string("__kernite_build_git", git_display),
                asm_string("__kernite_build_config_hash", config_hash),
                asm_string("__kernite_build_arch", args.arch),
                asm_string("__kernite_build_rustc", args.rustc_version),
                asm_string("__kernite_build_profile", args.profile),
                asm_string("__kernite_build_kernel_stack_size", args.kernel_stack_size),
                asm_string("__kernite_build_config_summary", summary),
                ".balign 8",
                ".global __kernite_build_info_end",
                "__kernite_build_info_end:",
                "",
            ]
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
