#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
#
# Extract `ROLE_*`, `LOCAL_ROLE_*`, `AT_TRONA_CAP_TABLE`, the cap-table
# magic/version, and the `CAP_TBL_{RIGHT,FLAG}_*` bits from
# `lib/trona/uapi/consts/kernel.rs` and emit:
#
#   * `lib/trona/rtld/common/cap_table_roles.h` — a C header included by
#     both the ELF rtld (`rtld_internal.h`) and the PE rtld
#     (`rtld_pe_internal.h`). Replaces the hand-maintained `#define`
#     blocks that previously lived in each header.
#
#   * `tools/role_map_data.py` — a Python module consumed by
#     `svc_caps_gen.py`. Provides `ROLE_IDS`, `LOCAL_ROLE_BASE`,
#     `LOCAL_ROLE_END`, magic/version, and the flag/right dicts so the
#     two generators never diverge.
#
# `kernel.rs` is the single source of truth; run `role_map_gen.py`
# whenever a `ROLE_*` or `CAP_TBL_*` constant changes and the
# downstream consumers pick up the new values automatically.

import argparse
import re
import sys
from pathlib import Path

ROLE_RE = re.compile(
    r"^\s*pub\s+const\s+(ROLE_[A-Z0-9_]+)\s*:\s*u32\s*=\s*"
    r"0x([0-9A-Fa-f]+)\s*;"
)
LOCAL_BASE_RE = re.compile(
    r"^\s*pub\s+const\s+LOCAL_ROLE_BASE\s*:\s*u32\s*=\s*0x([0-9A-Fa-f]+)\s*;"
)
LOCAL_END_RE = re.compile(
    r"^\s*pub\s+const\s+LOCAL_ROLE_END\s*:\s*u32\s*=\s*0x([0-9A-Fa-f]+)\s*;"
)
MAGIC_RE = re.compile(
    r"^\s*pub\s+const\s+TRONA_CAP_TABLE_MAGIC\s*:\s*u32\s*=\s*0x([0-9A-Fa-f]+)\s*;"
)
VERSION_RE = re.compile(
    r"^\s*pub\s+const\s+TRONA_CAP_TABLE_VERSION\s*:\s*u32\s*=\s*(\d+)\s*;"
)
AT_CAP_TABLE_RE = re.compile(
    r"^\s*pub\s+const\s+AT_TRONA_CAP_TABLE\s*:\s*u64\s*=\s*0x([0-9A-Fa-f]+)\s*;"
)
FLAG_RE = re.compile(
    r"^\s*pub\s+const\s+(CAP_TBL_FLAG_[A-Z0-9_]+)\s*:\s*u32\s*=\s*1\s*<<\s*(\d+)\s*;"
)
RIGHT_RE = re.compile(
    r"^\s*pub\s+const\s+(CAP_TBL_RIGHT_[A-Z0-9_]+)\s*:\s*u32\s*=\s*1\s*<<\s*(\d+)\s*;"
)


def die(msg: str) -> None:
    sys.stderr.write(f"role_map_gen: {msg}\n")
    sys.exit(1)


def parse_kernel_rs(path: Path):
    roles = {}
    flags = {}
    rights = {}
    local_base = None
    local_end = None
    magic = None
    version = None
    at_cap_table = None

    with path.open("r", encoding="utf-8") as fp:
        for line in fp:
            m = ROLE_RE.match(line)
            if m:
                roles[m.group(1)] = int(m.group(2), 16)
                continue
            m = FLAG_RE.match(line)
            if m:
                flags[m.group(1)] = 1 << int(m.group(2))
                continue
            m = RIGHT_RE.match(line)
            if m:
                rights[m.group(1)] = 1 << int(m.group(2))
                continue
            m = LOCAL_BASE_RE.match(line)
            if m:
                local_base = int(m.group(1), 16)
                continue
            m = LOCAL_END_RE.match(line)
            if m:
                local_end = int(m.group(1), 16)
                continue
            m = MAGIC_RE.match(line)
            if m:
                magic = int(m.group(1), 16)
                continue
            m = VERSION_RE.match(line)
            if m:
                version = int(m.group(1))
                continue
            m = AT_CAP_TABLE_RE.match(line)
            if m:
                at_cap_table = int(m.group(1), 16)
                continue

    if not roles:
        die(f"no ROLE_* constants found in {path}")
    if local_base is None or local_end is None:
        die(f"LOCAL_ROLE_BASE/LOCAL_ROLE_END missing from {path}")
    if magic is None or version is None:
        die(f"TRONA_CAP_TABLE_MAGIC/VERSION missing from {path}")
    if at_cap_table is None:
        die(f"AT_TRONA_CAP_TABLE missing from {path}")
    if not flags:
        die(f"no CAP_TBL_FLAG_* constants found in {path}")
    if not rights:
        die(f"no CAP_TBL_RIGHT_* constants found in {path}")

    return {
        "roles": roles,
        "flags": flags,
        "rights": rights,
        "local_base": local_base,
        "local_end": local_end,
        "magic": magic,
        "version": version,
        "at_cap_table": at_cap_table,
    }


def sort_roles(roles):
    # Sort numerically so generated output is stable and diff-friendly.
    return sorted(roles.items(), key=lambda kv: (kv[1], kv[0]))


def sort_bits(bits):
    return sorted(bits.items(), key=lambda kv: (kv[1], kv[0]))


def emit_c_header(data, source: Path) -> str:
    lines = []
    lines.append(
        f"/* GENERATED by tools/role_map_gen.py from {source.name}. "
        f"Do not edit. */"
    )
    lines.append("/* SPDX-License-Identifier: GPL-2.0-only */")
    lines.append("")
    lines.append("#ifndef TRONA_CAP_TABLE_ROLES_H")
    lines.append("#define TRONA_CAP_TABLE_ROLES_H")
    lines.append("")
    lines.append(f"#define AT_TRONA_CAP_TABLE      0x{data['at_cap_table']:04X}")
    lines.append("")
    lines.append(
        f"#define TRONA_CAP_TABLE_MAGIC    0x{data['magic']:08X}u  "
        f"/* \"SATC\" little-endian */"
    )
    lines.append(
        f"#define TRONA_CAP_TABLE_VERSION  {data['version']}u"
    )
    lines.append("")
    lines.append("/* System roles 0x0001..=0x00FF (public substrate ABI). */")
    for name, value in sort_roles(data["roles"]):
        lines.append(f"#define {name:<30} 0x{value:04X}u")
    lines.append("")
    lines.append(
        f"#define LOCAL_ROLE_BASE             0x{data['local_base']:04X}u"
    )
    lines.append(
        f"#define LOCAL_ROLE_END              0x{data['local_end']:04X}u"
    )
    lines.append("")
    lines.append("/* TronaCapEntryV1.rights bits — advisory. */")
    for name, value in sort_bits(data["rights"]):
        bit = value.bit_length() - 1
        lines.append(f"#define {name:<28} (1u << {bit})")
    lines.append("")
    lines.append("/* TronaCapEntryV1.flags bits. */")
    for name, value in sort_bits(data["flags"]):
        bit = value.bit_length() - 1
        lines.append(f"#define {name:<28} (1u << {bit})")
    lines.append("")
    lines.append("#endif /* TRONA_CAP_TABLE_ROLES_H */")
    return "\n".join(lines) + "\n"


def emit_python_data(data, source: Path) -> str:
    lines = []
    lines.append(
        f"# GENERATED by tools/role_map_gen.py from {source.name}. "
        f"Do not edit."
    )
    lines.append("# SPDX-License-Identifier: GPL-2.0-only")
    lines.append("")
    lines.append(f"AT_TRONA_CAP_TABLE = 0x{data['at_cap_table']:04X}")
    lines.append("")
    lines.append(f"TRONA_CAP_TABLE_MAGIC = 0x{data['magic']:08X}")
    lines.append(f"TRONA_CAP_TABLE_VERSION = {data['version']}")
    lines.append("")
    lines.append(f"LOCAL_ROLE_BASE = 0x{data['local_base']:04X}")
    lines.append(f"LOCAL_ROLE_END = 0x{data['local_end']:04X}")
    lines.append("LOCAL_ROLE_MOD = LOCAL_ROLE_END + 1 - LOCAL_ROLE_BASE")
    lines.append("")
    lines.append("ROLE_IDS = {")
    for name, value in sort_roles(data["roles"]):
        lines.append(f'    "{name}": 0x{value:04X},')
    lines.append("}")
    lines.append("")
    lines.append("CAP_TBL_RIGHT = {")
    for name, value in sort_bits(data["rights"]):
        short = name[len("CAP_TBL_RIGHT_"):]
        lines.append(f'    "{short}": 0x{value:08X},')
    lines.append("}")
    lines.append("")
    lines.append("CAP_TBL_FLAG = {")
    for name, value in sort_bits(data["flags"]):
        short = name[len("CAP_TBL_FLAG_"):]
        lines.append(f'    "{short}": 0x{value:08X},')
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="role map generator")
    ap.add_argument(
        "--input",
        required=True,
        help="path to lib/trona/uapi/consts/kernel.rs",
    )
    ap.add_argument(
        "--c-output",
        required=True,
        help="path to write generated cap_table_roles.h",
    )
    ap.add_argument(
        "--py-output",
        required=True,
        help="path to write generated role_map_data.py",
    )
    args = ap.parse_args()

    input_path = Path(args.input)
    if not input_path.is_file():
        die(f"input does not exist: {input_path}")
    data = parse_kernel_rs(input_path)

    c_out = Path(args.c_output)
    c_out.parent.mkdir(parents=True, exist_ok=True)
    c_out.write_text(emit_c_header(data, input_path), encoding="utf-8")

    py_out = Path(args.py_output)
    py_out.parent.mkdir(parents=True, exist_ok=True)
    py_out.write_text(emit_python_data(data, input_path), encoding="utf-8")


if __name__ == "__main__":
    main()
