# SaltyOS Userland Build
# SPDX-License-Identifier: GPL-2.0-only

# Userland is only built when build_userland=true
# Each component is a separate executable

subdir('init')
subdir('rtld')
subdir('console')
subdir('nameserv')
subdir('mmsrv')
subdir('procmgr')
subdir('vfs')
subdir('display')
subdir('ttyd')
subdir('getty')
subdir('test_runner')
subdir('hello')
